# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Your own specialized rules go here
Bundler/OrderedGems:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Include:
    - "app/**/*"
    - "config/routes.rb"
    - "lib/**/*"
    - "spec/**/*"
    - "test/**/*"
    - "Gemfile"
