default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: kanban_development
  cache:
    <<: *default
    database: kanban_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: kanban_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: kanban_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: kanban_test

production:
  primary: &primary
    <<: *default
    database: kanban_appdev_academy_production
    host: <%= ENV["POSTGRES_HOST"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary
    database: kanban_appdev_academy_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary
    database: kanban_appdev_academy_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary
    database: kanban_appdev_academy_production_cable
    migrations_paths: db/cable_migrate
